/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author Bernardo
 */
public class TelaEstResultadoCorreto extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaEstResultadoCorreto
     */
    public TelaEstResultadoCorreto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        btVeificar = new javax.swing.JButton();
        tcasa = new javax.swing.JLabel();
        tEmpate = new javax.swing.JLabel();
        tVisitante = new javax.swing.JLabel();
        dasd = new javax.swing.JLabel();
        sdasd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t3x0 = new javax.swing.JLabel();
        t2x1 = new javax.swing.JLabel();
        t2x0 = new javax.swing.JLabel();
        t1x0 = new javax.swing.JLabel();
        t2x2 = new javax.swing.JLabel();
        t1x1 = new javax.swing.JLabel();
        t0x0 = new javax.swing.JLabel();
        t0x3 = new javax.swing.JLabel();
        t1x2 = new javax.swing.JLabel();
        t0x2 = new javax.swing.JLabel();
        t0x1 = new javax.swing.JLabel();
        dasd1 = new javax.swing.JLabel();
        dasd2 = new javax.swing.JLabel();
        dasd3 = new javax.swing.JLabel();
        tOddsCasa = new javax.swing.JLabel();
        tOddsEmpate = new javax.swing.JLabel();
        tOddsVisitante = new javax.swing.JLabel();

        setClosable(true);

        jLabel9.setText("URL :");

        txtUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrlActionPerformed(evt);
            }
        });

        btVeificar.setText("Veificar");
        btVeificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVeificarActionPerformed(evt);
            }
        });

        tcasa.setText("CASA");

        tEmpate.setText("EMPATE");

        tVisitante.setText("VISITANTE");

        dasd.setText("1 x 0");

        sdasd.setText("2 x 0");

        jLabel3.setText("2 x 1");

        jLabel4.setText("3 x 0");

        jLabel5.setText("0 x 0");

        jLabel7.setText("2 x 2");

        jLabel8.setText("1 x 1");

        jLabel10.setText("0 x 1");

        jLabel11.setText("0 x 3");

        jLabel12.setText("1 x 2");

        jLabel13.setText("0 x 2");

        t3x0.setText("-----");

        t2x1.setText("-----");

        t2x0.setText("-----");

        t1x0.setText("-----");

        t2x2.setText("-----");

        t1x1.setText("-----");

        t0x0.setText("-----");

        t0x3.setText("-----");

        t1x2.setText("-----");

        t0x2.setText("-----");

        t0x1.setText("-----");

        dasd1.setText("Odds");

        dasd2.setText("Odds");

        dasd3.setText("Odds");

        tOddsCasa.setText("-----");

        tOddsEmpate.setText("-----");

        tOddsVisitante.setText("-----");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btVeificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dasd)
                                    .addComponent(sdasd)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(dasd1))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tOddsCasa)
                                    .addComponent(t1x0)
                                    .addComponent(t2x0)
                                    .addComponent(t2x1)
                                    .addComponent(t3x0))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEmpate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t0x0)
                                    .addComponent(t1x1)
                                    .addComponent(t2x2)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dasd2)
                                .addGap(18, 18, 18)
                                .addComponent(tOddsEmpate)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dasd3)
                                .addGap(18, 18, 18)
                                .addComponent(tOddsVisitante))
                            .addComponent(tVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t0x1)
                                    .addComponent(t0x2)
                                    .addComponent(t1x2)
                                    .addComponent(t0x3))))))
                .addContainerGap(583, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVeificar)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcasa, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addComponent(tEmpate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tVisitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dasd1)
                    .addComponent(dasd2)
                    .addComponent(dasd3)
                    .addComponent(tOddsCasa)
                    .addComponent(tOddsEmpate)
                    .addComponent(tOddsVisitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dasd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sdasd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(t1x0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2x0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2x1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t3x0))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(t0x0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t1x1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t2x2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(t0x1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t0x2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t1x2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t0x3)))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlActionPerformed

    private void btVeificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVeificarActionPerformed
        // TODO add your handling code here:
        String url = txtUrl.getText();
        Document document;
        
        //Nome times
        try {
            document = Jsoup.connect(url).get();
            Elements elements = document.getElementsByClass("runners-container");
            Elements ss= elements.select("[class=home-runner]");
            tcasa.setText(ss.text());
            
            ss= elements.select("[class=away-runner]");
            tVisitante.setText(ss.text());
            
            elements = document.getElementsByClass("correct-score-collapsed-container collapsed-container");
            ss= elements.select("[class=runner-item collapsed-runner-2]");
            Elements as = ss.select("[class*=com-bet-button]");
            t1x0.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-5]");
            as = ss.select("[class*=com-bet-button]");
            t2x0.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-6]");
            as = ss.select("[class*=com-bet-button]");
            t2x1.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-10]");
            as = ss.select("[class*=com-bet-button]");
            t3x0.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-1]");
            as = ss.select("[class*=com-bet-button]");
            t0x0.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-3]");
            as = ss.select("[class*=com-bet-button]");
            t1x1.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-7]");
            as = ss.select("[class*=com-bet-button]");
            t2x2.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-4]");
            as = ss.select("[class*=com-bet-button]");
            t0x1.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-9]");
            as = ss.select("[class*=com-bet-button]");
            t0x2.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-8]");
            as = ss.select("[class*=com-bet-button]");
            t1x2.setText(as.text());
            
            ss= elements.select("[class=runner-item collapsed-runner-16]");
            as = ss.select("[class*=com-bet-button]");
            t0x3.setText(as.text());
            
            elements = document.getElementsByClass("runner-list3 minimarketview-1056");
            as = elements.select("[class*=runner-item]:eq(0)");
            Elements de = as.select("[class*=com-bet-button]");
            tOddsCasa.setText(de.text());
            
            elements = document.getElementsByClass("runner-list3 minimarketview-1056");
            as = elements.select("[class*=runner-item]:eq(1)");
            de = as.select("[class*=com-bet-button]");
            tOddsEmpate.setText(de.text());
            
            elements = document.getElementsByClass("runner-list3 minimarketview-1056");
            as = elements.select("[class*=runner-item]:eq(2)");
            de = as.select("[class*=com-bet-button]");
            tOddsVisitante.setText(de.text());
            
        } catch (IOException ex) {
            Logger.getLogger(TelaEstResultadoCorreto.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        

        

        
    }//GEN-LAST:event_btVeificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVeificar;
    private javax.swing.JLabel dasd;
    private javax.swing.JLabel dasd1;
    private javax.swing.JLabel dasd2;
    private javax.swing.JLabel dasd3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel sdasd;
    private javax.swing.JLabel t0x0;
    private javax.swing.JLabel t0x1;
    private javax.swing.JLabel t0x2;
    private javax.swing.JLabel t0x3;
    private javax.swing.JLabel t1x0;
    private javax.swing.JLabel t1x1;
    private javax.swing.JLabel t1x2;
    private javax.swing.JLabel t2x0;
    private javax.swing.JLabel t2x1;
    private javax.swing.JLabel t2x2;
    private javax.swing.JLabel t3x0;
    private javax.swing.JLabel tEmpate;
    private javax.swing.JLabel tOddsCasa;
    private javax.swing.JLabel tOddsEmpate;
    private javax.swing.JLabel tOddsVisitante;
    private javax.swing.JLabel tVisitante;
    private javax.swing.JLabel tcasa;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables
}
