/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.ProximoJogo;
import model.bean.Tipo;
import model.dao.ProximoJogoDAO;
import model.dao.TipoDAO;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

/**
 *
 * @author Bernardo
 */
public class Tela_NowProxJogos extends javax.swing.JInternalFrame {
    /**
     * Creates new form TelaCadastroJogo
     */
    private String link;

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }
    
    public Tela_NowProxJogos() throws IOException {
        initComponents();
        readJTable();
        DefaultTableModel modelo = (DefaultTableModel) jTJogo.getModel();
        // IGNORE A LINHA DE CIMA, SÓ USEI PARA MOSTRA_LO DA ONDE TIREI O TABLEMODEL 
        TableRowSorter tableSorter = new TableRowSorter(modelo);
        jTJogo.setRowSorter(tableSorter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTJogo = new javax.swing.JTable();
        jBFinalizar = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jTJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Casa", "Visitante", "Link"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTJogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTJogo);

        jBFinalizar.setText("Finalizar Aposta");
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFinalizar)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTJogoMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, jTJogo.getValueAt(jTJogo.getSelectedRow(), 3).toString());
        if(jTJogo.getSelectedRow()!=-1){            
            //txtCasa.setText(jTJogo.getValueAt(jTJogo.getSelectedRow(), 1).toString());

        }else{
            JOptionPane.showMessageDialog(null,"Selecione!!!!");
        }
        
    }//GEN-LAST:event_jTJogoMouseClicked

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        try {
            // TODO add your handling code here:
            String ss=jTJogo.getValueAt(jTJogo.getSelectedRow(), 3).toString();
    
            Tela_NowPrevisaoCantos tela = new Tela_NowPrevisaoCantos();
            this.setLink(ss);
        
            TelaPrincipal.jDesktopPane1.add(tela);
            tela.setLink(ss);
            tela.readJTable();
            tela.setVisible(true);
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Tela_NowProxJogos.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jBFinalizarActionPerformed
    public void readJTable() throws IOException{
        DefaultTableModel modelo = (DefaultTableModel) jTJogo.getModel();
        modelo.setNumRows(0);
        
        java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(java.util.logging.Level.OFF); /* comment out to turn off annoying htmlunit warnings */
        WebClient webClient = new WebClient();
        HtmlPage currentPage = webClient.getPage("http://info.nowgoal.com/en/League/2019/4.html");
        String Source = currentPage.asXml();
        
        Document doo =Jsoup.parse(Source);
        
        Elements tabela = doo.select("[id=Table3]");
        Elements items = tabela.select("tr:gt(1)");  
        for(Element it: items){
            String data = it.select("td:eq(1)").text();
            String timeA = it.select("td:eq(2)").select("a").text();
            String linkTimeA = it.select("td:eq(9)").select("a").attr("href");
            String timeB = it.select("td:eq(4)").select("a").text();
            System.out.println("\n"+ data+" "+ timeA+" x "+timeB+" ---- "+linkTimeA);
            
            modelo.addRow(new Object[]{data,timeA,timeB,linkTimeA});
        }       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTJogo;
    // End of variables declaration//GEN-END:variables
}
