/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.scripts.JO;
import model.bean.Jogo;
import model.bean.Tipo;
import model.dao.JogoDAO;
import model.dao.TipoDAO;

/**
 *
 * @author Bernardo
 */
public class TelaCadastroJogo extends javax.swing.JInternalFrame {
    private int codTip;

    public int getCodTip() {
        return codTip;
    }

    public void setCodTip(int codTip) {
        this.codTip = codTip;
    }
    

    /**
     * Creates new form TelaCadastroJogo
     */
    public TelaCadastroJogo() {
        initComponents();
        readJTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCasa = new javax.swing.JTextField();
        jBSalvar = new javax.swing.JButton();
        txtVisitante = new javax.swing.JTextField();
        txtOdds = new javax.swing.JTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtValor = new javax.swing.JTextField();
        jBExcluir = new javax.swing.JButton();
        jBAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTJogo = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtafavor = new javax.swing.JComboBox();
        jBFinalizar = new javax.swing.JButton();
        txtStatus = new javax.swing.JComboBox();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jLabel1.setText("Casa");

        jLabel2.setText("Visitante");

        jLabel3.setText("Odds");

        jLabel4.setText("Data");

        jLabel6.setText("Valor");

        jBSalvar.setText("Salvar");
        jBSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalvarActionPerformed(evt);
            }
        });

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtData.setText("\n  ");
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Alterar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jTJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codjog", "Casa", "Visitante", "Valor", "Afavor", "Data", "odds", "STATUS", "Retorno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTJogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTJogo);

        jLabel7.setText("Afavor");

        txtafavor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "X1", "X", "2", "X2", " " }));

        jBFinalizar.setText("Finalizar Aposta");
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "D" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtOdds, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52)
                                .addComponent(txtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(52, 52, 52))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(53, 53, 53)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(43, 43, 43)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtafavor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCasa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVisitante))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtOdds))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtafavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBFinalizar)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jBAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jBExcluir)
                        .addGap(59, 59, 59))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalvarActionPerformed
        // TODO add your handling code here:
        Jogo jogo = new Jogo();
        JogoDAO dao = new JogoDAO();
        
        Tipo tipo = new Tipo();
        Tipo tipoInser = new Tipo();
        TipoDAO tipdao = new TipoDAO();

        jogo.setTimeA(txtCasa.getText());
        jogo.setTimeB(txtVisitante.getText());
        jogo.setAposta(Double.parseDouble(txtValor.getText()));
        jogo.setData(txtData.getText());
        jogo.setOdds(Double.parseDouble(txtOdds.getText()));
        jogo.setAfavor(txtafavor.getSelectedItem().toString());
        jogo.setRetorno((jogo.getAposta()*jogo.getOdds())-jogo.getAposta());
        jogo.setCoddtip(this.getCodTip());
        dao.create(jogo);
        readJTable();
        
        tipo.setCodtip(this.getCodTip());
        tipoInser=tipdao.readRetorno(tipo);
        tipdao.updateTipo(tipoInser);
        
    }//GEN-LAST:event_jBSalvarActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        Jogo jogo = new Jogo();
        JogoDAO dao = new JogoDAO();
        Tipo tipo = new Tipo();
        Tipo tipoInser = new Tipo();
        TipoDAO tipdao = new TipoDAO();
        
        jogo.setCodjog(Integer.parseInt(jTJogo.getValueAt(jTJogo.getSelectedRow(), 0).toString()));
        dao.excluir(jogo);
        
        DefaultTableModel dtmJogo = (DefaultTableModel) jTJogo.getModel();
        dtmJogo.removeRow(jTJogo.getSelectedRow()); 
        
        tipo.setCodtip(dao.selecionarCodTip(jogo));
        tipoInser=tipdao.readRetorno(tipo);
        tipdao.updateTipo(tipoInser);
        
        
        
        
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        // TODO add your handling code here:
        if(jTJogo.getSelectedRow()!=-1){   
             Jogo jogo = new Jogo();
             JogoDAO dao = new JogoDAO();
             Tipo tipo = new Tipo();
             Tipo tipoInser = new Tipo();
             TipoDAO tipdao = new TipoDAO();
             
             jogo.setTimeA(txtCasa.getText());
             jogo.setTimeB(txtVisitante.getText());
             jogo.setAposta(Double.parseDouble(txtValor.getText()));
             jogo.setData(txtData.getText());
             jogo.setOdds(Double.parseDouble(txtOdds.getText()));
             jogo.setAfavor(txtafavor.getSelectedItem().toString());
             jogo.setRetorno((jogo.getAposta()*jogo.getOdds())-jogo.getAposta());

             
             jogo.setCodjog(Integer.parseInt(jTJogo.getValueAt(jTJogo.getSelectedRow(), 0).toString()));
             dao.update(jogo);
             
             tipo.setCodtip(dao.selecionarCodTip(jogo));
             tipoInser=tipdao.readRetorno(tipo);
             tipdao.updateTipo(tipoInser);
             
             jTJogo.setValueAt(txtCasa.getText(), jTJogo.getSelectedRow(), 1);
             jTJogo.setValueAt(txtVisitante.getText(), jTJogo.getSelectedRow(), 2);
             jTJogo.setValueAt(txtValor.getText(), jTJogo.getSelectedRow(), 3);
             jTJogo.setValueAt(txtafavor.getSelectedItem().toString(), jTJogo.getSelectedRow(), 4);
             jTJogo.setValueAt(txtData.getText(), jTJogo.getSelectedRow(), 5);
             jTJogo.setValueAt(txtOdds.getText(), jTJogo.getSelectedRow(), 6);
             
             txtCasa.setText("");
             txtVisitante.setText("");
             txtValor.setText("");
             txtafavor.setSelectedIndex(0);
             txtData.setText("");
             txtOdds.setText("");
             
            
             readJTable();
        }
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jTJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTJogoMouseClicked
        // TODO add your handling code here:
        if(jTJogo.getSelectedRow()!=-1){            
            txtCasa.setText(jTJogo.getValueAt(jTJogo.getSelectedRow(), 1).toString());
            txtVisitante.setText(jTJogo.getValueAt(jTJogo.getSelectedRow(), 2).toString());
            txtValor.setText(jTJogo.getValueAt(jTJogo.getSelectedRow(), 3).toString());
            txtafavor.setSelectedIndex(0);
            txtData.setText(jTJogo.getValueAt(jTJogo.getSelectedRow(), 5).toString());
            txtOdds.setText(jTJogo.getValueAt(jTJogo.getSelectedRow(), 6).toString());
        }else{
            JOptionPane.showMessageDialog(null,"Selecione!!!!");
        }
        
    }//GEN-LAST:event_jTJogoMouseClicked

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        // TODO add your handling code here:
        Tipo tipo = new Tipo();
        Tipo tipoInser = new Tipo();
        TipoDAO tipdao = new TipoDAO();
        
        if(jTJogo.getSelectedRow()!=-1){   
             Jogo jogo = new Jogo();
             JogoDAO dao = new JogoDAO();
             
             
             if(txtStatus.getSelectedItem().equals("V")){
                    jogo.setStatus("VITORIA");             
             }else{
                 jogo.setStatus("DERROTA");
             }
             
           
             jogo.setCodjog(Integer.parseInt(jTJogo.getValueAt(jTJogo.getSelectedRow(), 0).toString()));
             dao.updateStatus(jogo);
             
             
             tipo.setCodtip(dao.selecionarCodTip(jogo));
             tipoInser=tipdao.readRetorno(tipo);
             tipdao.updateTipo(tipoInser);
             readJTable();
        }
    }//GEN-LAST:event_jBFinalizarActionPerformed
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTJogo.getModel();
        modelo.setNumRows(0);
        JogoDAO dao = new JogoDAO();
        
        for(Jogo j : dao.read(this.getCodTip())){
            modelo.addRow(new Object[]{
                j.getCodjog(),
                j.getTimeA(),
                j.getTimeB(),
                j.getAposta(),
                j.getAfavor(),
                j.getData(),
                j.getOdds(),
                j.getStatus(),
                j.getRetorno()
            });
        }    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JButton jBSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTJogo;
    private javax.swing.JTextField txtCasa;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtOdds;
    private javax.swing.JComboBox txtStatus;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtVisitante;
    private javax.swing.JComboBox txtafavor;
    // End of variables declaration//GEN-END:variables
}
