/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Jogo;
import model.bean.LigaCantos;
import model.bean.Pais;
import model.bean.ProximoJogo;
import model.bean.TimeCantos;
import model.dao.JogoDAO;
import model.dao.LigaCantosDAO;
import model.dao.ProximoJogoDAO;
import model.dao.TimeCantosDAO;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author Bernardo
 */
public class TelaDadosCantosAtualizada extends javax.swing.JInternalFrame {
    private ArrayList<TimeCantos> ListaTimes = new ArrayList<>();

    /**
     * Creates new form TelaDadosCantos
     */
    public TelaDadosCantosAtualizada() throws IOException {
        initComponents();
        atualizarPaiss();
        tornarInvisivel();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cbliga = new javax.swing.JComboBox();
        Cbvisitnte = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btGerar = new javax.swing.JButton();
        CbCasa = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TLiga = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtliga = new javax.swing.JLabel();
        jPCasa = new javax.swing.JPanel();
        lMedCasaAfavor = new javax.swing.JLabel();
        lMedCasaContra = new javax.swing.JLabel();
        lMedCasaTotal = new javax.swing.JLabel();
        lMedCasaAfavor1 = new javax.swing.JLabel();
        lMedCasaContra1 = new javax.swing.JLabel();
        CasaTotal1T = new javax.swing.JLabel();
        CasaContra1T = new javax.swing.JLabel();
        CasaAfavor1T = new javax.swing.JLabel();
        txtCasa1T = new javax.swing.JLabel();
        txtCasa2T = new javax.swing.JLabel();
        txtCasaFT = new javax.swing.JLabel();
        CasaAfavor2T = new javax.swing.JLabel();
        CasaContra2T = new javax.swing.JLabel();
        CasaTotal2T = new javax.swing.JLabel();
        CasaContraFT = new javax.swing.JLabel();
        CasaTotalFT = new javax.swing.JLabel();
        CasaAfavorFT = new javax.swing.JLabel();
        jAtualizaar = new javax.swing.JButton();
        jPVisitante = new javax.swing.JPanel();
        lMedCasaContra3 = new javax.swing.JLabel();
        CasaTotalFT1 = new javax.swing.JLabel();
        CasaContraFT1 = new javax.swing.JLabel();
        CasaAfavor2T1 = new javax.swing.JLabel();
        CasaAfavorFT1 = new javax.swing.JLabel();
        lMedCasaTotal1 = new javax.swing.JLabel();
        txtCasaFT1 = new javax.swing.JLabel();
        CasaTotal1T1 = new javax.swing.JLabel();
        lMedCasaAfavor2 = new javax.swing.JLabel();
        txtCasa2T1 = new javax.swing.JLabel();
        CasaContra1T1 = new javax.swing.JLabel();
        CasaAfavor1T1 = new javax.swing.JLabel();
        CasaContra2T1 = new javax.swing.JLabel();
        txtCasa1T1 = new javax.swing.JLabel();
        CasaTotal2T1 = new javax.swing.JLabel();
        lMedCasaContra2 = new javax.swing.JLabel();
        jPVisitante1 = new javax.swing.JPanel();
        lMedCasaContra4 = new javax.swing.JLabel();
        CasaTotalFT2 = new javax.swing.JLabel();
        Predt2 = new javax.swing.JLabel();
        CasaAfavorFT2 = new javax.swing.JLabel();
        lMedCasaTotal2 = new javax.swing.JLabel();
        txtCasaFT2 = new javax.swing.JLabel();
        CasaTotal1T2 = new javax.swing.JLabel();
        lMedCasaAfavor3 = new javax.swing.JLabel();
        txtCasa2T2 = new javax.swing.JLabel();
        Predt1 = new javax.swing.JLabel();
        txtCasa1T2 = new javax.swing.JLabel();
        CasaTotal2T2 = new javax.swing.JLabel();
        btPais = new javax.swing.JButton();
        Cblpais = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TProximosJogos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btSalvarCantos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPalpiteCantos = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 153, 0));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        setClosable(true);
        setTitle("Dados Cantos");
        setPreferredSize(new java.awt.Dimension(1040, 680));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1040, 670));

        jLabel1.setText("Liga :");

        Cbliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbligaActionPerformed(evt);
            }
        });

        jLabel2.setText("Visitante:");

        btGerar.setText("Selecionar Liga");
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        CbCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCasaActionPerformed(evt);
            }
        });

        jLabel3.setText("Casa :");

        TLiga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Faz", "Sofre", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TLiga);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Liga:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 50));

        txtliga.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtliga.setForeground(new java.awt.Color(255, 0, 0));
        txtliga.setPreferredSize(new java.awt.Dimension(100, 50));

        jPCasa.setBackground(new java.awt.Color(255, 255, 255));
        jPCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Casa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPCasa.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPCasa.setPreferredSize(new java.awt.Dimension(400, 150));

        lMedCasaAfavor.setText("Média Afavor :");

        lMedCasaContra.setText("Média Contra :");

        lMedCasaTotal.setText("Média Total :");

        txtCasa1T.setText("1T");

        txtCasa2T.setText("2T");

        txtCasaFT.setText("FT");

        javax.swing.GroupLayout jPCasaLayout = new javax.swing.GroupLayout(jPCasa);
        jPCasa.setLayout(jPCasaLayout);
        jPCasaLayout.setHorizontalGroup(
            jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasaLayout.createSequentialGroup()
                .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lMedCasaContra1)
                        .addGap(152, 152, 152))
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMedCasaContra)
                            .addComponent(lMedCasaTotal)
                            .addComponent(lMedCasaAfavor))
                        .addGap(36, 36, 36)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCasaLayout.createSequentialGroup()
                                .addComponent(txtCasa1T)
                                .addGap(50, 50, 50)
                                .addComponent(txtCasa2T)
                                .addGap(50, 50, 50)
                                .addComponent(txtCasaFT))
                            .addGroup(jPCasaLayout.createSequentialGroup()
                                .addComponent(CasaAfavor1T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaAfavor2T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaAfavorFT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCasaLayout.createSequentialGroup()
                                .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CasaContra1T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CasaTotal1T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCasaLayout.createSequentialGroup()
                                        .addComponent(CasaContra2T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CasaContraFT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPCasaLayout.createSequentialGroup()
                                        .addComponent(CasaTotal2T, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CasaTotalFT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lMedCasaAfavor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
        jPCasaLayout.setVerticalGroup(
            jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasaLayout.createSequentialGroup()
                .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lMedCasaAfavor1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCasa1T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCasa2T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCasaFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lMedCasaAfavor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaAfavor1T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaAfavor2T, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaAfavorFT, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CasaContra1T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lMedCasaContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaContra2T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaContraFT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lMedCasaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaTotal1T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaTotal2T, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaTotalFT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lMedCasaContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jAtualizaar.setText("Selecionar Times");
        jAtualizaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizaarActionPerformed(evt);
            }
        });

        jPVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPVisitante.setPreferredSize(new java.awt.Dimension(400, 150));

        lMedCasaTotal1.setText("Média Total :");

        txtCasaFT1.setText("FT");

        lMedCasaAfavor2.setText("Média Afavor :");

        txtCasa2T1.setText("2T");

        txtCasa1T1.setText("1T");

        lMedCasaContra2.setText("Média Contra :");

        javax.swing.GroupLayout jPVisitanteLayout = new javax.swing.GroupLayout(jPVisitante);
        jPVisitante.setLayout(jPVisitanteLayout);
        jPVisitanteLayout.setHorizontalGroup(
            jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitanteLayout.createSequentialGroup()
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVisitanteLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lMedCasaContra3))
                    .addGroup(jPVisitanteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMedCasaContra2)
                            .addComponent(lMedCasaTotal1)
                            .addComponent(lMedCasaAfavor2))
                        .addGap(36, 36, 36)
                        .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPVisitanteLayout.createSequentialGroup()
                                .addComponent(txtCasa1T1)
                                .addGap(50, 50, 50)
                                .addComponent(txtCasa2T1)
                                .addGap(50, 50, 50)
                                .addComponent(txtCasaFT1))
                            .addGroup(jPVisitanteLayout.createSequentialGroup()
                                .addComponent(CasaAfavor1T1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaAfavor2T1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaAfavorFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPVisitanteLayout.createSequentialGroup()
                                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CasaContra1T1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CasaTotal1T1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPVisitanteLayout.createSequentialGroup()
                                        .addComponent(CasaContra2T1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CasaContraFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPVisitanteLayout.createSequentialGroup()
                                        .addComponent(CasaTotal2T1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CasaTotalFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPVisitanteLayout.setVerticalGroup(
            jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitanteLayout.createSequentialGroup()
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCasa1T1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCasa2T1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCasaFT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMedCasaAfavor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaAfavor1T1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaAfavor2T1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaAfavorFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CasaContra1T1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lMedCasaContra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaContra2T1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaContraFT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMedCasaTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotal1T1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotal2T1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotalFT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMedCasaContra3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPVisitante1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Predição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPVisitante1.setPreferredSize(new java.awt.Dimension(400, 150));

        lMedCasaTotal2.setText("Média Total :");

        txtCasaFT2.setText("FT");

        lMedCasaAfavor3.setText("Cantos :");

        txtCasa2T2.setText("2T");

        txtCasa1T2.setText("1T");

        javax.swing.GroupLayout jPVisitante1Layout = new javax.swing.GroupLayout(jPVisitante1);
        jPVisitante1.setLayout(jPVisitante1Layout);
        jPVisitante1Layout.setHorizontalGroup(
            jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitante1Layout.createSequentialGroup()
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVisitante1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lMedCasaContra4))
                    .addGroup(jPVisitante1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMedCasaTotal2)
                            .addComponent(lMedCasaAfavor3))
                        .addGap(36, 36, 36)
                        .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPVisitante1Layout.createSequentialGroup()
                                .addComponent(txtCasa1T2)
                                .addGap(50, 50, 50)
                                .addComponent(txtCasa2T2)
                                .addGap(50, 50, 50)
                                .addComponent(txtCasaFT2))
                            .addGroup(jPVisitante1Layout.createSequentialGroup()
                                .addComponent(Predt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Predt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaAfavorFT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPVisitante1Layout.createSequentialGroup()
                                .addComponent(CasaTotal1T2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaTotal2T2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaTotalFT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPVisitante1Layout.setVerticalGroup(
            jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitante1Layout.createSequentialGroup()
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCasa1T2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCasa2T2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCasaFT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMedCasaAfavor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Predt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Predt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaAfavorFT2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMedCasaTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotal1T2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotal2T2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotalFT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMedCasaContra4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btPais.setText("Selecionar País");
        btPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaisActionPerformed(evt);
            }
        });

        Cblpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CblpaisActionPerformed(evt);
            }
        });

        jLabel5.setText("Pais :");

        TProximosJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Casa", "Visitante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TProximosJogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TProximosJogosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TProximosJogos);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Proximos Jogos ");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 50));

        btSalvarCantos.setText("Salvar");
        btSalvarCantos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCantosActionPerformed(evt);
            }
        });

        jLabel7.setText("N° Cantos :");

        txtPalpiteCantos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "11.0", "12.0", "13.0", "14.0", "15.0", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Cbliga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Cblpais, 0, 150, Short.MAX_VALUE)
                                    .addComponent(CbCasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cbvisitnte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btPais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jAtualizaar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                    .addComponent(jPVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPVisitante1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtliga, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPalpiteCantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvarCantos)
                        .addGap(76, 76, 76))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btGerar)
                                    .addComponent(jLabel1)
                                    .addComponent(Cbliga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(Cblpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btPais)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAtualizaar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(CbCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Cbvisitnte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtliga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPVisitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btSalvarCantos)
                                .addComponent(jLabel7)
                                .addComponent(txtPalpiteCantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        // TODO add your handling code here:
        tornarInvisivel();
        LigaCantos l = new LigaCantos();
        l= (LigaCantos) Cbliga.getSelectedItem();
        ListaTimes.clear();
        try {
            atualizarTabela(l.getLink());
        } catch (IOException ex) {
            Logger.getLogger(TelaDadosCantosAtualizada.class.getName()).log(Level.SEVERE, null, ex);
        }
        tornarInvisivel();
    }//GEN-LAST:event_btGerarActionPerformed

    private void jAtualizaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizaarActionPerformed
        // TODO add your handling code here:
        tornarVisivel();
        TimeCantos timeCasa = (TimeCantos) CbCasa.getSelectedItem();
        TimeCantos timeVisitante = (TimeCantos) Cbvisitnte.getSelectedItem();
        
        CasaAfavor1T.setText(timeCasa.getmCantosFeitosHT().toString());
        CasaContra1T.setText(timeCasa.getmCantosSofridosHT().toString());
        double total1t =timeCasa.getmCantosFeitosHT()+timeCasa.getmCantosSofridosHT();
        CasaTotal1T.setText(String.format("%.2f", total1t));
        
        CasaAfavor1T1.setText(timeVisitante.getmCantosFeitosHT().toString());
        CasaContra1T1.setText(timeVisitante.getmCantosSofridosHT().toString());
        double vtotal1t =timeVisitante.getmCantosFeitosHT()+timeVisitante.getmCantosSofridosHT();
        CasaTotal1T1.setText(String.format("%.2f", vtotal1t));        
        
        CasaAfavorFT.setText(timeCasa.getmCantosFeitos().toString());
        CasaContraFT.setText(timeCasa.getmCantosSofridos().toString());
        double totalft =timeCasa.getmCantosFeitos()+timeCasa.getmCantosSofridos();
        CasaTotalFT.setText(String.format("%.2f", totalft));
        
        CasaAfavorFT1.setText(timeVisitante.getmCantosFeitos().toString());
        CasaContraFT1.setText(timeVisitante.getmCantosSofridos().toString());
        double vtotalft =timeVisitante.getmCantosFeitos()+timeVisitante.getmCantosSofridos();
        CasaTotalFT1.setText(String.format("%.2f", vtotalft));
        
        CasaAfavor2T.setText(String.format("%.2f",timeCasa.getmCantosFeitos()-timeCasa.getmCantosFeitosHT()));
        CasaContra2T.setText(String.format("%.2f",timeCasa.getmCantosSofridos()-timeCasa.getmCantosSofridosHT()));
        double total2t =(timeCasa.getmCantosFeitos()-timeCasa.getmCantosFeitosHT())+(timeCasa.getmCantosSofridos()-timeCasa.getmCantosSofridosHT());
        CasaTotal2T.setText(String.format("%.2f", total2t));
        
        CasaAfavor2T1.setText(String.format("%.2f",timeVisitante.getmCantosFeitos()-timeVisitante.getmCantosFeitosHT()));
        CasaContra2T1.setText(String.format("%.2f",timeVisitante.getmCantosSofridos()-timeVisitante.getmCantosSofridosHT()));
        double vtotal2t =(timeVisitante.getmCantosFeitos()-timeVisitante.getmCantosFeitosHT())+(timeVisitante.getmCantosSofridos()-timeVisitante.getmCantosSofridosHT());
        CasaTotal2T1.setText(String.format("%.2f", vtotal2t));
        
        Predt1.setText(String.format("%.2f",(total1t+vtotal1t)/2));
        Predt2.setText(String.format("%.2f",(total2t+vtotal2t)/2));
        CasaAfavorFT2.setText(String.format("%.2f",(totalft+vtotalft)/2));
        
        jPCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, timeCasa.getNome(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, timeVisitante.getNome(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N

    }//GEN-LAST:event_jAtualizaarActionPerformed

    public void AcharDados(TimeCantos timeCasa,TimeCantos timeVisitante){
        tornarVisivel();
        
        CasaAfavor1T.setText(timeCasa.getmCantosFeitosHT().toString());
        CasaContra1T.setText(timeCasa.getmCantosSofridosHT().toString());
        double total1t =timeCasa.getmCantosFeitosHT()+timeCasa.getmCantosSofridosHT();
        CasaTotal1T.setText(String.format("%.2f", total1t));
        
        CasaAfavor1T1.setText(timeVisitante.getmCantosFeitosHT().toString());
        CasaContra1T1.setText(timeVisitante.getmCantosSofridosHT().toString());
        double vtotal1t =timeVisitante.getmCantosFeitosHT()+timeVisitante.getmCantosSofridosHT();
        CasaTotal1T1.setText(String.format("%.2f", vtotal1t));        
        
        CasaAfavorFT.setText(timeCasa.getmCantosFeitos().toString());
        CasaContraFT.setText(timeCasa.getmCantosSofridos().toString());
        double totalft =timeCasa.getmCantosFeitos()+timeCasa.getmCantosSofridos();
        CasaTotalFT.setText(String.format("%.2f", totalft));
        
        CasaAfavorFT1.setText(timeVisitante.getmCantosFeitos().toString());
        CasaContraFT1.setText(timeVisitante.getmCantosSofridos().toString());
        double vtotalft =timeVisitante.getmCantosFeitos()+timeVisitante.getmCantosSofridos();
        CasaTotalFT1.setText(String.format("%.2f", vtotalft));
        
        CasaAfavor2T.setText(String.format("%.2f",timeCasa.getmCantosFeitos()-timeCasa.getmCantosFeitosHT()));
        CasaContra2T.setText(String.format("%.2f",timeCasa.getmCantosSofridos()-timeCasa.getmCantosSofridosHT()));
        double total2t =(timeCasa.getmCantosFeitos()-timeCasa.getmCantosFeitosHT())+(timeCasa.getmCantosSofridos()-timeCasa.getmCantosSofridosHT());
        CasaTotal2T.setText(String.format("%.2f", total2t));
        
        CasaAfavor2T1.setText(String.format("%.2f",timeVisitante.getmCantosFeitos()-timeVisitante.getmCantosFeitosHT()));
        CasaContra2T1.setText(String.format("%.2f",timeVisitante.getmCantosSofridos()-timeVisitante.getmCantosSofridosHT()));
        double vtotal2t =(timeVisitante.getmCantosFeitos()-timeVisitante.getmCantosFeitosHT())+(timeVisitante.getmCantosSofridos()-timeVisitante.getmCantosSofridosHT());
        CasaTotal2T1.setText(String.format("%.2f", vtotal2t));
        
        Predt1.setText(String.format("%.2f",(total1t+vtotal1t)/2));
        Predt2.setText(String.format("%.2f",(total2t+vtotal2t)/2));
        CasaAfavorFT2.setText(String.format("%.2f",(totalft+vtotalft)/2));
        
        jPCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, timeCasa.getNome(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, timeVisitante.getNome(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N

    
    }
    private void CbligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbligaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbligaActionPerformed

    private void CbCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCasaActionPerformed

    private void btPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaisActionPerformed
        // TODO add your handling code here:
        tornarInvisivel();
        Cbliga.removeAllItems();
        DefaultTableModel modelop = (DefaultTableModel) TProximosJogos.getModel();
        modelop.setNumRows(0);
        DefaultTableModel modelo = (DefaultTableModel) TLiga.getModel();
        modelo.setNumRows(0);
        
        Pais p = new Pais();
        p = (Pais) Cblpais.getSelectedItem();
        try {
            atualizarLigas(p.getLink());
        } catch (IOException ex) {
            Logger.getLogger(TelaDadosCantosAtualizada.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPaisActionPerformed

    private void CblpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CblpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CblpaisActionPerformed

    private void btSalvarCantosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCantosActionPerformed
        // TODO add your handling code here:
        ProximoJogo p = new ProximoJogo();
        ProximoJogoDAO pdao = new ProximoJogoDAO();
        
        p.setLiga(Cbliga.getSelectedItem().toString());
        p.setT1(Double.parseDouble(Predt1.getText().replace(",",".")));
        p.setT2(Double.parseDouble(Predt2.getText().replace(",",".")));
        
     
        try {
            p.setData(TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),0).toString());
            p.setCasa(TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),1).toString());
            p.setVisitante(TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),2).toString());
            p.setPrevisao(txtPalpiteCantos.getSelectedItem().toString());

            pdao.create(p);
        } catch (Exception e) {
        }
        
	
        
    }//GEN-LAST:event_btSalvarCantosActionPerformed

    private void TProximosJogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TProximosJogosMouseClicked
        // TODO add your handling code here:

        String timeSelecionadoCasa = TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),1).toString();
        String timeSelecionadoVisitante = TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),2).toString();
        for(TimeCantos tt:ListaTimes){
            if(tt.getNome().equals(timeSelecionadoCasa)){
                for(TimeCantos t:ListaTimes){
                    if(t.getNome().equals(timeSelecionadoVisitante)){
                        AcharDados(tt, t);
                    }            
                }
            }            
        }
        
    }//GEN-LAST:event_TProximosJogosMouseClicked
    
    public void readJTable(){
        LigaCantos lcantos= (LigaCantos) Cbliga.getSelectedItem();
        DefaultTableModel modelo = (DefaultTableModel) TLiga.getModel();
        modelo.setNumRows(0);
        TimeCantosDAO dao = new TimeCantosDAO();
        
        for(TimeCantos t : dao.read(lcantos.getCodlig())){
            modelo.addRow(new Object[]{
                t.getNome(),t.getmCantosFeitos(),t.getmCantosSofridos(),t.getmCantosTotais()
            });
        }    
    }
    public void atualizarTabela(String rLink) throws IOException{
        CbCasa.removeAllItems();
        Cbvisitnte.removeAllItems();
        DefaultTableModel modelo = (DefaultTableModel) TLiga.getModel();
        modelo.setNumRows(0);
        DefaultTableModel modelop = (DefaultTableModel) TProximosJogos.getModel();
        modelop.setNumRows(0);
                            
        String url = "https://www.fctables.com/";                   
        String url1 = url+rLink;
                Document documentoNomeLiga = Jsoup.connect(url1).get();
                Elements TabelaJogos = documentoNomeLiga.select("[class=games-box livescore_body]");
                Elements jogo = TabelaJogos.select("[id*=game]");
                String nomeLiga;
                for(Element e : jogo){
                    String data =e.select("[class*=date_unix]").attr("title");
                    String timeCasa =e.select("[class*=game_hover]").select("[class*=home]").text();
                    String timeVisitante =e.select("[class*=game_hover]").select("[class*=away]").text();              
                    modelop.addRow(new Object[]{data,timeCasa,timeVisitante});
                }
                
        
        String url3=url+rLink+"corners/";
        Document document3 = Jsoup.connect(url3).get();
        Elements tabelaTbody = document3.select("tbody");
        Elements itemsTr = tabelaTbody.select("tr"); 
          
                    for(Element element1 : itemsTr){
                        try {
                            TimeCantos time = new TimeCantos();
                            String Times = element1.select("td:eq(1)").text();
                            Double MCantosFeitos = Double.parseDouble(element1.select("td:eq(6)").text());
                            Double MCantosSofridos = Double.parseDouble(element1.select("td:eq(14)").text());
                            Double MCantosTotais = Double.parseDouble(element1.select("td:eq(2)").text());
                            Double MCantosFeitosHT = Double.parseDouble(element1.select("td:eq(7)").text());
                            Double MCantosSofridosHT = Double.parseDouble(element1.select("td:eq(15)").text());
                            
                            time.setNome(Times);
                            time.setmCantosFeitos(MCantosFeitos);
                            time.setmCantosFeitosHT(MCantosFeitosHT);
                            time.setmCantosSofridos(MCantosSofridos);
                            time.setmCantosSofridosHT(MCantosSofridosHT);
                            time.setmCantosTotais(MCantosTotais);
                            CbCasa.addItem(time);
                            Cbvisitnte.addItem(time);
                            ListaTimes.add(time);
                            
                            modelo.addRow(new Object[]{time.getNome(),time.getmCantosFeitos(),time.getmCantosSofridos(),time.getmCantosTotais()});
                    
                        } catch (Exception e) {
                        }  
                    }
    }
 
    public void atualizarLigas(String rLink) throws IOException{
        String url = "https://www.fctables.com/";
        String url2=url+rLink;
        Document document2 = Jsoup.connect(url2).get();
        Elements tabelaLigas = document2.select("[class=col-xs-6 col-sm-4 col-lg-3 col-md-3]");
          
        for(Element element : tabelaLigas){
              try {
                  LigaCantos l = new LigaCantos();
                  Elements linkLiga = element.select("[class=logo-image]").select("a[href]");
                  Elements linkLiga1 = element.select("[class=detail truncate]").select("a[href]");
                  String rLinkLiga = linkLiga.attr("href").toString();
                  String nomeLiga1 = linkLiga1.text();
                  
                  l.setNome(nomeLiga1);
                  l.setLink(rLinkLiga);
                  
                  Cbliga.addItem(l);
             } catch (Exception e) {
             }                                    
       }
    }
    public void atualizarPaiss() throws IOException{
        String url = "https://www.fctables.com/";
              
        Document document = Jsoup.connect(url).get();
        Elements tabela = document.select("[onclick=alphabet_c(this)]:gt(2)");
        Elements items = tabela.select("[data-href]");
      
        for(Element element2 : items){
            try {
                Pais p = new Pais();
                String rLink = element2.attr("data-href").toString();
                String nome = element2.text();
                p.setNome(nome);
                p.setLink(rLink);
                Cblpais.addItem(p);
            } catch (Exception e) {
            }
       }
        
            //Cblpais.addItem();   
        
    }
    
    public void tornarInvisivel(){
        
        jPCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Casa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        
        txtCasa1T.setVisible(false);
        txtCasa2T.setVisible(false);
        txtCasaFT.setVisible(false);
        txtCasa1T1.setVisible(false);
        txtCasa2T1.setVisible(false);
        txtCasaFT1.setVisible(false);
        txtCasa1T2.setVisible(false);
        txtCasa2T2.setVisible(false);
        txtCasaFT2.setVisible(false); 
        
        lMedCasaAfavor2.setVisible(false);
        lMedCasaTotal2.setVisible(false);
        lMedCasaAfavor3.setVisible(false);
        lMedCasaContra2.setVisible(false);
        lMedCasaTotal1.setVisible(false);
        lMedCasaAfavor.setVisible(false);
        lMedCasaContra.setVisible(false);
        lMedCasaTotal.setVisible(false);
        
        CasaAfavor1T.setVisible(false);
        CasaTotal1T.setVisible(false);
        CasaContra1T.setVisible(false);
        
        Predt1.setVisible(false);
        Predt2.setVisible(false);
        CasaAfavorFT2.setVisible(false);

    }
    public void tornarVisivel(){
        txtCasa1T.setVisible(true);
        txtCasa2T.setVisible(true);
        txtCasaFT.setVisible(true);
        txtCasa1T1.setVisible(true);
        txtCasa2T1.setVisible(true);
        txtCasaFT1.setVisible(true);  
        txtCasa1T2.setVisible(true);
        txtCasa2T2.setVisible(true);
        txtCasaFT2.setVisible(true); 
        
        lMedCasaAfavor2.setVisible(true);
        lMedCasaAfavor3.setVisible(true);
        lMedCasaContra2.setVisible(true);
        lMedCasaTotal1.setVisible(true);
        lMedCasaAfavor.setVisible(true);
        lMedCasaContra.setVisible(true);
        lMedCasaTotal.setVisible(true);
        
        CasaAfavor1T.setVisible(true);
        CasaTotal1T.setVisible(true);
        CasaContra1T.setVisible(true);
        
        Predt1.setVisible(true);
        Predt2.setVisible(true);
        CasaAfavorFT2.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CasaAfavor1T;
    private javax.swing.JLabel CasaAfavor1T1;
    private javax.swing.JLabel CasaAfavor2T;
    private javax.swing.JLabel CasaAfavor2T1;
    private javax.swing.JLabel CasaAfavorFT;
    private javax.swing.JLabel CasaAfavorFT1;
    private javax.swing.JLabel CasaAfavorFT2;
    private javax.swing.JLabel CasaContra1T;
    private javax.swing.JLabel CasaContra1T1;
    private javax.swing.JLabel CasaContra2T;
    private javax.swing.JLabel CasaContra2T1;
    private javax.swing.JLabel CasaContraFT;
    private javax.swing.JLabel CasaContraFT1;
    private javax.swing.JLabel CasaTotal1T;
    private javax.swing.JLabel CasaTotal1T1;
    private javax.swing.JLabel CasaTotal1T2;
    private javax.swing.JLabel CasaTotal2T;
    private javax.swing.JLabel CasaTotal2T1;
    private javax.swing.JLabel CasaTotal2T2;
    private javax.swing.JLabel CasaTotalFT;
    private javax.swing.JLabel CasaTotalFT1;
    private javax.swing.JLabel CasaTotalFT2;
    private javax.swing.JComboBox CbCasa;
    private javax.swing.JComboBox Cbliga;
    private javax.swing.JComboBox Cblpais;
    private javax.swing.JComboBox Cbvisitnte;
    private javax.swing.JLabel Predt1;
    private javax.swing.JLabel Predt2;
    private javax.swing.JTable TLiga;
    private javax.swing.JTable TProximosJogos;
    private javax.swing.JButton btGerar;
    private javax.swing.JButton btPais;
    private javax.swing.JButton btSalvarCantos;
    private javax.swing.JButton jAtualizaar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPCasa;
    private javax.swing.JPanel jPVisitante;
    private javax.swing.JPanel jPVisitante1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lMedCasaAfavor;
    private javax.swing.JLabel lMedCasaAfavor1;
    private javax.swing.JLabel lMedCasaAfavor2;
    private javax.swing.JLabel lMedCasaAfavor3;
    private javax.swing.JLabel lMedCasaContra;
    private javax.swing.JLabel lMedCasaContra1;
    private javax.swing.JLabel lMedCasaContra2;
    private javax.swing.JLabel lMedCasaContra3;
    private javax.swing.JLabel lMedCasaContra4;
    private javax.swing.JLabel lMedCasaTotal;
    private javax.swing.JLabel lMedCasaTotal1;
    private javax.swing.JLabel lMedCasaTotal2;
    private javax.swing.JLabel txtCasa1T;
    private javax.swing.JLabel txtCasa1T1;
    private javax.swing.JLabel txtCasa1T2;
    private javax.swing.JLabel txtCasa2T;
    private javax.swing.JLabel txtCasa2T1;
    private javax.swing.JLabel txtCasa2T2;
    private javax.swing.JLabel txtCasaFT;
    private javax.swing.JLabel txtCasaFT1;
    private javax.swing.JLabel txtCasaFT2;
    private javax.swing.JComboBox txtPalpiteCantos;
    private javax.swing.JLabel txtliga;
    // End of variables declaration//GEN-END:variables
}
