/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.LigaCantos;
import model.bean.LigaNow;
import model.bean.Pais;
import model.bean.ProximoJogo;
import model.bean.TimeCantos;
import model.dao.ProximoJogoDAO;
import model.dao.TimeCantosDAO;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author Bernardo
 */
public class Tela_Now extends javax.swing.JInternalFrame {
    private Document documento;
    private String linkTemporada;
    private String linkJogo;

    public String getLinkTemporada() {
        return linkTemporada;
    }

    public void setLinkTemporada(String linkTemporada) {
        this.linkTemporada = linkTemporada;
    }

    public String getLinkJogo() {
        return linkJogo;
    }

    public void setLinkJogo(String linkJogo) {
        this.linkJogo = linkJogo;
    }

    public Document getDocumento() {
        return documento;
    }

    public void setDocumento(Document documento) {
        this.documento = documento;
    }
    

    /**
     * Creates new form TelaDadosCantos
     */
    public Tela_Now() throws IOException {
        initComponents();
        java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(java.util.logging.Level.OFF); /* comment out to turn off annoying htmlunit warnings */
        WebClient webClient = new WebClient();
        HtmlPage currentPage = webClient.getPage("http://info.nowgoal.com/");
        String texto = currentPage.asXml();
    
        Document documento = Jsoup.parse(texto);
        this.setDocumento(documento);
        readJTable(documento);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cbliga = new javax.swing.JComboBox();
        Cbvisitnte = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btBuscarLiga = new javax.swing.JButton();
        CbCasa = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TLiga = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtliga = new javax.swing.JLabel();
        jAtualizaar = new javax.swing.JButton();
        btPais = new javax.swing.JButton();
        Cblpais = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TProximosJogos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btSalvarCantos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtPalpiteCantos = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        CbTemporada = new javax.swing.JComboBox();
        btSelecionarTemp = new javax.swing.JButton();
        jPCasa = new javax.swing.JPanel();
        lMedCasaAfavor = new javax.swing.JLabel();
        lMedCasaContra = new javax.swing.JLabel();
        lMedCasaTotal = new javax.swing.JLabel();
        lMedCasaAfavor1 = new javax.swing.JLabel();
        lMedCasaContra1 = new javax.swing.JLabel();
        txtCasaFT = new javax.swing.JLabel();
        CasaContraFT = new javax.swing.JLabel();
        CasaTotalFT = new javax.swing.JLabel();
        CasaAfavorFT = new javax.swing.JLabel();
        jPVisitante = new javax.swing.JPanel();
        lMedCasaContra3 = new javax.swing.JLabel();
        CasaTotalFT1 = new javax.swing.JLabel();
        CasaContraFT1 = new javax.swing.JLabel();
        CasaAfavorFT1 = new javax.swing.JLabel();
        lMedCasaTotal1 = new javax.swing.JLabel();
        txtCasaFT1 = new javax.swing.JLabel();
        lMedCasaAfavor2 = new javax.swing.JLabel();
        lMedCasaContra2 = new javax.swing.JLabel();
        jPVisitante1 = new javax.swing.JPanel();
        lMedCasaContra4 = new javax.swing.JLabel();
        CasaTotalFT2 = new javax.swing.JLabel();
        CasaAfavorFT2 = new javax.swing.JLabel();
        lMedCasaTotal2 = new javax.swing.JLabel();
        txtCasaFT2 = new javax.swing.JLabel();
        CasaTotal1T2 = new javax.swing.JLabel();
        lMedCasaAfavor3 = new javax.swing.JLabel();
        CasaTotal2T2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 0));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 102, 0)));
        setClosable(true);
        setTitle("Dados Cantos");
        setPreferredSize(new java.awt.Dimension(1070, 560));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 670));

        jLabel1.setText("Liga :");

        Cbliga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbligaActionPerformed(evt);
            }
        });

        jLabel2.setText("Visitante:");

        btBuscarLiga.setText("Selecionar Liga");
        btBuscarLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarLigaActionPerformed(evt);
            }
        });

        CbCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbCasaActionPerformed(evt);
            }
        });

        jLabel3.setText("Casa :");

        TLiga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "Faz", "Sofre", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TLiga);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Liga:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 50));

        txtliga.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtliga.setForeground(new java.awt.Color(255, 0, 0));
        txtliga.setPreferredSize(new java.awt.Dimension(100, 50));

        jAtualizaar.setText("Selecionar Times");
        jAtualizaar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtualizaarActionPerformed(evt);
            }
        });

        btPais.setText("Selecionar País");
        btPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaisActionPerformed(evt);
            }
        });

        Cblpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CblpaisActionPerformed(evt);
            }
        });

        jLabel5.setText("Pais :");

        TProximosJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Casa", "Visitante", "Link"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TProximosJogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TProximosJogosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TProximosJogos);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Proximos Jogos ");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 50));

        btSalvarCantos.setText("Salvar");
        btSalvarCantos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCantosActionPerformed(evt);
            }
        });

        jLabel7.setText("N° Cantos :");

        txtPalpiteCantos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "11.0", "12.0", "13.0", "14.0", "15.0", " " }));

        jLabel8.setText("Temporada :");

        CbTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTemporadaActionPerformed(evt);
            }
        });

        btSelecionarTemp.setText("Selecionar Temporada");
        btSelecionarTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarTempActionPerformed(evt);
            }
        });

        jPCasa.setBackground(new java.awt.Color(255, 255, 255));
        jPCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Casa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPCasa.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPCasa.setPreferredSize(new java.awt.Dimension(400, 150));

        lMedCasaAfavor.setText("Média Afavor :");

        lMedCasaContra.setText("Média Contra :");

        lMedCasaTotal.setText("Média Total :");

        txtCasaFT.setText("FT");

        javax.swing.GroupLayout jPCasaLayout = new javax.swing.GroupLayout(jPCasa);
        jPCasa.setLayout(jPCasaLayout);
        jPCasaLayout.setHorizontalGroup(
            jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasaLayout.createSequentialGroup()
                .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lMedCasaContra1)
                        .addGap(152, 152, 152))
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMedCasaContra)
                            .addComponent(lMedCasaTotal)
                            .addComponent(lMedCasaAfavor))
                        .addGap(18, 18, 18)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCasaLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtCasaFT))
                            .addComponent(CasaAfavorFT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CasaContraFT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CasaTotalFT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lMedCasaAfavor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
        jPCasaLayout.setVerticalGroup(
            jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCasaLayout.createSequentialGroup()
                .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lMedCasaAfavor1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPCasaLayout.createSequentialGroup()
                        .addComponent(txtCasaFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lMedCasaAfavor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaAfavorFT, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lMedCasaContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaContraFT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lMedCasaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CasaTotalFT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lMedCasaContra1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPVisitante.setPreferredSize(new java.awt.Dimension(400, 150));

        lMedCasaTotal1.setText("Média Total :");

        txtCasaFT1.setText("FT");

        lMedCasaAfavor2.setText("Média Afavor :");

        lMedCasaContra2.setText("Média Contra :");

        javax.swing.GroupLayout jPVisitanteLayout = new javax.swing.GroupLayout(jPVisitante);
        jPVisitante.setLayout(jPVisitanteLayout);
        jPVisitanteLayout.setHorizontalGroup(
            jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitanteLayout.createSequentialGroup()
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVisitanteLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lMedCasaContra3))
                    .addGroup(jPVisitanteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lMedCasaContra2)
                            .addComponent(lMedCasaTotal1)
                            .addComponent(lMedCasaAfavor2))
                        .addGap(18, 18, 18)
                        .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPVisitanteLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtCasaFT1))
                            .addComponent(CasaAfavorFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CasaContraFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CasaTotalFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPVisitanteLayout.setVerticalGroup(
            jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitanteLayout.createSequentialGroup()
                .addComponent(txtCasaFT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMedCasaAfavor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaAfavorFT1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMedCasaContra2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaContraFT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPVisitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMedCasaTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotalFT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMedCasaContra3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPVisitante1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Predição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jPVisitante1.setPreferredSize(new java.awt.Dimension(400, 150));

        lMedCasaTotal2.setText("Média Total :");

        txtCasaFT2.setText("FT");

        lMedCasaAfavor3.setText("Cantos :");

        javax.swing.GroupLayout jPVisitante1Layout = new javax.swing.GroupLayout(jPVisitante1);
        jPVisitante1.setLayout(jPVisitante1Layout);
        jPVisitante1Layout.setHorizontalGroup(
            jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitante1Layout.createSequentialGroup()
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPVisitante1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lMedCasaContra4))
                    .addGroup(jPVisitante1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPVisitante1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(CasaTotal2T2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CasaTotalFT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPVisitante1Layout.createSequentialGroup()
                                .addComponent(lMedCasaAfavor3)
                                .addGap(18, 18, 18)
                                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCasaFT2)
                                    .addComponent(CasaAfavorFT2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPVisitante1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lMedCasaTotal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CasaTotal1T2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPVisitante1Layout.setVerticalGroup(
            jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPVisitante1Layout.createSequentialGroup()
                .addComponent(txtCasaFT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lMedCasaAfavor3)
                    .addComponent(CasaAfavorFT2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMedCasaTotal2)
                    .addComponent(CasaTotal1T2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPVisitante1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CasaTotal2T2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CasaTotalFT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lMedCasaContra4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbvisitnte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Cblpais, javax.swing.GroupLayout.Alignment.LEADING, 0, 125, Short.MAX_VALUE)
                                .addComponent(Cbliga, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbTemporada, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CbCasa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBuscarLiga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPais, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSelecionarTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAtualizaar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPalpiteCantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvarCantos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPVisitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtliga, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPVisitante1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtliga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Cblpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Cbliga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscarLiga))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CbTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btSelecionarTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CbCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAtualizaar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Cbvisitnte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPVisitante, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btSalvarCantos)
                                .addComponent(jLabel7)
                                .addComponent(txtPalpiteCantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSelecionarTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarTempActionPerformed
        // TODO add your handling code here:
        LigaNow l = new LigaNow();
        l= (LigaNow) CbTemporada.getSelectedItem();
        BuscarJogos(l.getLink());
    }//GEN-LAST:event_btSelecionarTempActionPerformed

    private void CbTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTemporadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbTemporadaActionPerformed

    private void btSalvarCantosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCantosActionPerformed
        // TODO add your handling code here:
        ProximoJogo p = new ProximoJogo();
        ProximoJogoDAO pdao = new ProximoJogoDAO();
        
        p.setLiga(Cbliga.getSelectedItem().toString());
        p.setT1(Double.parseDouble(CasaTotalFT.getText().replace(",",".")));
        p.setT2(Double.parseDouble(CasaTotalFT1.getText().replace(",",".")));
        
     
        try {
            p.setData(TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),0).toString());
            p.setCasa(TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),1).toString());
            p.setVisitante(TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(),2).toString());
            p.setPrevisao(txtPalpiteCantos.getSelectedItem().toString());

            pdao.create(p);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btSalvarCantosActionPerformed

    private void TProximosJogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TProximosJogosMouseClicked
        try {
            // TODO add your handling code here:
            PrevisaoTimes(TProximosJogos.getValueAt(TProximosJogos.getSelectedRow(), 3).toString());
        } catch (IOException ex) {
            Logger.getLogger(Tela_Now.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_TProximosJogosMouseClicked

    private void CblpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CblpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CblpaisActionPerformed

    private void btPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaisActionPerformed
        // TODO add your handling code here:
        Pais pais = (Pais) Cblpais.getSelectedItem();
        try {
            BuscarLiga(pais.getLink(), this.getDocumento());
        } catch (IOException ex) {
            Logger.getLogger(Tela_Now.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPaisActionPerformed

    private void jAtualizaarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtualizaarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAtualizaarActionPerformed

    private void CbCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbCasaActionPerformed

    private void btBuscarLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarLigaActionPerformed
        // TODO add your handling code here:
        tornarInvisivel();
        LigaNow l = (LigaNow) Cbliga.getSelectedItem();
        try {
            this.setLinkTemporada(BuscarTemporada(l.getPais(),l.getLink(), this.getDocumento()));
        } catch (IOException ex) {
            Logger.getLogger(Tela_Now.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBuscarLigaActionPerformed

    private void CbligaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbligaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbligaActionPerformed

    public void AcharDados(TimeCantos timeCasa,TimeCantos timeVisitante){
           
    }    
    public void readJTable(Document documento) throws IOException{
        Elements tabela = documento.select("[id=allSclassList]");
        Elements paises = tabela.select("[class=divList]");
        Elements ligas = documento.select("[class=floatDiv]").select("[class=ulDiv]:eq(0)").select("li[onmouseover*=showSeason]").select("a[href*=java]:eq(0)");
        
        
        
        for(Element it:paises){
            String buscar =it.attr("id")+"div";
            Pais p = new Pais();
            p.setNome(it.text());
            p.setLink(buscar);
            Cblpais.addItem(p);
        }
    }
    
    public void BuscarLiga(String ligsa,Document documento) throws IOException{
            Elements liga = documento.select("[id="+ligsa+"]").select("[class=ulDiv]:eq(0)").select("li[onmouseover*=showSeason]");
            for(Element its:liga){
                String nome  = its.select("a[href*=java]:eq(0)").text();
                Elements temporada = its.select("[class=inner_ul]").select("li:eq(0)");//.select("a[href]:eq(0)");
                //System.out.println("  "+nome+"  -  "+temporada.text()+"  -  "+temporada.select("a").attr("href"));
                LigaNow l = new LigaNow();
                l.setNome(nome);
                l.setLink(its.select("li").attr("onmouseover"));
                l.setPais(ligsa);
                Cbliga.addItem(l);
            }     
    }
    
    public String BuscarTemporada(String ligsa,String temporada1,Document documento) throws IOException{
            Elements liga = documento.select("[id="+ligsa+"]").select("[class=ulDiv]:eq(0)").select("li[onmouseover=showSeason(this,event,0)]");
            Elements temporada = liga.select("[class=inner_ul]").select("li");
            String link = "";
            for(Element its:temporada){
                String nome  = its.text();
                link = its.select("a").attr("href");
                System.out.println(link);
                LigaNow l = new LigaNow();
                l.setNome(nome);
                l.setLink(link);
                CbTemporada.addItem(l);
            }     
            JOptionPane.showMessageDialog(this, "link sss : "+link);
            return link;
    }
    
    public void BuscarJogos(String LinkTemporada){
        DefaultTableModel modelo = (DefaultTableModel) TProximosJogos.getModel();
        modelo.setNumRows(0);
        
        JOptionPane.showMessageDialog(this,"LLink : "+LinkTemporada);
        
        java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(java.util.logging.Level.OFF); /* comment out to turn off annoying htmlunit warnings */
        WebClient webClient = new WebClient();
        HtmlPage currentPage;
        try {
            currentPage = webClient.getPage("http://info.nowgoal.com"+LinkTemporada);String Source = currentPage.asXml();
        
            Document doo =Jsoup.parse(Source);
        
            Elements tabela = doo.select("[id=Table3]");
            Elements items = tabela.select("tr:gt(1)");  
            for(Element it: items){
                String data = it.select("td:eq(1)").text();
                String timeA = it.select("td:eq(2)").select("a").text();
                String linkTimeA = it.select("td:eq(9)").select("a").attr("href");
                String timeB = it.select("td:eq(4)").select("a").text();
                System.out.println("\n"+ data+" "+ timeA+" x "+timeB+" ---- "+linkTimeA);
            
                modelo.addRow(new Object[]{data,timeA,timeB,linkTimeA});
            }    
        } catch (IOException ex) {
            Logger.getLogger(Tela_Now.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    
    public void PrevisaoTimes(String link) throws IOException{
        java.util.logging.Logger.getLogger("com.gargoylesoftware").setLevel(java.util.logging.Level.OFF); /* comment out to turn off annoying htmlunit warnings */
        WebClient webClient = new WebClient();
        HtmlPage currentPage = webClient.getPage(link);
        String Source = currentPage.asXml();
        
        Document doo =Jsoup.parse(Source);
        
        Elements nomeA = doo.select("[class=sclassName]");
        ArrayList<String> noo = new ArrayList<>();
        for(Element item:nomeA){
            noo.add(item.text());
        }
        jPCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, noo.get(0), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, noo.get(1), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
         
        
        //Tabela 11
        Elements tabela = doo.select("[id=table_v1]");
        Elements items = tabela.select("tr:gt(2)").select("[id*=tr]");  
        
        Double mCasaFeitos=0.0;
        Double mCasaSofridos=0.0;
        int cont=0;
        for(Element it: items){
            String data = it.select("td:eq(1)").text();
            String timeA = it.select("td:eq(2)").select("a").text();
            String timeB = it.select("td:eq(6)").select("a").text();
            String cantos = it.select("td:eq(5)").text();           
            int traco=0;
            for(int i=0;i<cantos.length();i++){
                if(cantos.substring(i,i+1).equals("-")){ 
                    traco=i;
                }
            }
            Double nCantosCasa = Double.parseDouble(cantos.substring(0,traco));
            Double nCantosVisitante = Double.parseDouble(cantos.substring(traco+1,cantos.length()));
            cont++;
            
            mCasaFeitos=mCasaFeitos+nCantosCasa;
            mCasaSofridos=mCasaSofridos+nCantosVisitante;
            
            
        }
                   
        mCasaFeitos=mCasaFeitos/cont;
        mCasaSofridos=mCasaSofridos/cont;
        
        CasaAfavorFT.setText(mCasaFeitos.toString());
        CasaContraFT.setText(mCasaSofridos.toString());
        CasaTotalFT.setText(String.valueOf(mCasaSofridos+mCasaFeitos));
        
        
        
        
        
        //Tabela 11
        Elements tabela2 = doo.select("[id=table_v2]");
        Elements items2 = tabela2.select("tr:gt(2)").select("[id*=tr]");  
        
        Double mCasaFeitos2=0.0;
        Double mCasaSofridos2=0.0;
        int cont2=0;
        for(Element it: items2){
            String data = it.select("td:eq(1)").text();
            String timeA = it.select("td:eq(2)").select("a").text();
            String timeB = it.select("td:eq(6)").select("a").text();
            String cantos = it.select("td:eq(5)").text();           
            int traco=0;
            for(int i=0;i<cantos.length();i++){
                if(cantos.substring(i,i+1).equals("-")){ 
                    traco=i;
                }
            }
            Double nCantosCasa2 = Double.parseDouble(cantos.substring(0,traco));
            Double nCantosVisitante2 = Double.parseDouble(cantos.substring(traco+1,cantos.length()));
            cont2++;
            
            mCasaFeitos2=mCasaFeitos2+nCantosCasa2;
            mCasaSofridos2=mCasaSofridos2+nCantosVisitante2;
            
        }        
        mCasaFeitos2=mCasaFeitos2/cont2;
        mCasaSofridos2=mCasaSofridos2/cont2;
        
        CasaAfavorFT1.setText(mCasaFeitos2.toString());
        CasaContraFT1.setText(mCasaSofridos2.toString());
        CasaTotalFT1.setText(String.valueOf(mCasaFeitos2+mCasaSofridos2));
        
        
        CasaAfavorFT2.setText(String.valueOf((mCasaFeitos2+mCasaSofridos2+mCasaSofridos+mCasaFeitos)/2));
        
       // Double af = Double.parseDouble(CasaTotalFT.toString());
       // Double co = Double.parseDouble(CasaTotalFT1.toString());
       // Double total = (af+co)/2;
        
       // CasaTotal1T2.setText(total.toString());
    
    }
    
    public void tornarInvisivel(){
        
        jPCasa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Casa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        jPVisitante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Visitante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        txtCasaFT.setVisible(false);
        txtCasaFT1.setVisible(false);
        txtCasaFT2.setVisible(false); 
        
        lMedCasaAfavor2.setVisible(false);
        lMedCasaTotal2.setVisible(false);
        lMedCasaAfavor3.setVisible(false);
        lMedCasaContra2.setVisible(false);
        lMedCasaTotal1.setVisible(false);
        lMedCasaAfavor.setVisible(false);
        lMedCasaContra.setVisible(false);
        lMedCasaTotal.setVisible(false);
        
        CasaAfavorFT2.setVisible(false);

    }
    public void tornarVisivel(){
        txtCasaFT.setVisible(true);
        txtCasaFT1.setVisible(true);  
        txtCasaFT2.setVisible(true); 
        
        lMedCasaAfavor2.setVisible(true);
        lMedCasaAfavor3.setVisible(true);
        lMedCasaContra2.setVisible(true);
        lMedCasaTotal1.setVisible(true);
        lMedCasaAfavor.setVisible(true);
        lMedCasaContra.setVisible(true);
        lMedCasaTotal.setVisible(true);
        

        CasaAfavorFT2.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CasaAfavorFT;
    private javax.swing.JLabel CasaAfavorFT1;
    private javax.swing.JLabel CasaAfavorFT2;
    private javax.swing.JLabel CasaContraFT;
    private javax.swing.JLabel CasaContraFT1;
    private javax.swing.JLabel CasaTotal1T2;
    private javax.swing.JLabel CasaTotal2T2;
    private javax.swing.JLabel CasaTotalFT;
    private javax.swing.JLabel CasaTotalFT1;
    private javax.swing.JLabel CasaTotalFT2;
    private javax.swing.JComboBox CbCasa;
    private javax.swing.JComboBox CbTemporada;
    private javax.swing.JComboBox Cbliga;
    private javax.swing.JComboBox Cblpais;
    private javax.swing.JComboBox Cbvisitnte;
    private javax.swing.JTable TLiga;
    private javax.swing.JTable TProximosJogos;
    private javax.swing.JButton btBuscarLiga;
    private javax.swing.JButton btPais;
    private javax.swing.JButton btSalvarCantos;
    private javax.swing.JButton btSelecionarTemp;
    private javax.swing.JButton jAtualizaar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPCasa;
    private javax.swing.JPanel jPVisitante;
    private javax.swing.JPanel jPVisitante1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lMedCasaAfavor;
    private javax.swing.JLabel lMedCasaAfavor1;
    private javax.swing.JLabel lMedCasaAfavor2;
    private javax.swing.JLabel lMedCasaAfavor3;
    private javax.swing.JLabel lMedCasaContra;
    private javax.swing.JLabel lMedCasaContra1;
    private javax.swing.JLabel lMedCasaContra2;
    private javax.swing.JLabel lMedCasaContra3;
    private javax.swing.JLabel lMedCasaContra4;
    private javax.swing.JLabel lMedCasaTotal;
    private javax.swing.JLabel lMedCasaTotal1;
    private javax.swing.JLabel lMedCasaTotal2;
    private javax.swing.JLabel txtCasaFT;
    private javax.swing.JLabel txtCasaFT1;
    private javax.swing.JLabel txtCasaFT2;
    private javax.swing.JComboBox txtPalpiteCantos;
    private javax.swing.JLabel txtliga;
    // End of variables declaration//GEN-END:variables
}
