/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.google.gson.Gson;
import java.awt.Desktop;
import java.io.InputStreamReader;
import java.io.Reader;
import java.net.URI;
import java.net.URL;
import java.net.URLEncoder;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import jdk.nashorn.internal.scripts.JO;
import model.bean.Jogo;
import model.bean.ProximoJogo;
import model.bean.Tipo;
import model.dao.JogoDAO;
import model.dao.ProximoJogoDAO;
import model.dao.TipoDAO;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

/**
 *
 * @author Bernardo
 */
public class TelaVisualizarEscanteios extends javax.swing.JInternalFrame {
    /**
     * Creates new form TelaCadastroJogo
     */
    public TelaVisualizarEscanteios() {
        initComponents();
        readJTable();
        DefaultTableModel modelo = (DefaultTableModel) jTJogo.getModel();
        // IGNORE A LINHA DE CIMA, SÓ USEI PARA MOSTRA_LO DA ONDE TIREI O TABLEMODEL 
        TableRowSorter tableSorter = new TableRowSorter(modelo);
        jTJogo.setRowSorter(tableSorter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTJogo = new javax.swing.JTable();
        jBFinalizar = new javax.swing.JButton();
        txtStatus = new javax.swing.JComboBox();
        jPesquisar = new javax.swing.JButton();
        jResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        btTrocar = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1000, 500));

        jTJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Data", "Casa", "Visitante", "Previsao", "STATUS", "1° Tempo", "2° Tempo", "Liga", "Resultados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTJogoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTJogo);

        jBFinalizar.setText("Finalizar Aposta");
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        txtStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "D" }));

        jPesquisar.setText("Procurar");
        jPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesquisarActionPerformed(evt);
            }
        });

        jResultado.setText("Resultado: ");

        btTrocar.setText("Trocar");
        btTrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTrocarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(16, Short.MAX_VALUE)
                        .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBFinalizar)
                                .addGap(18, 18, 18)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btTrocar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jResultado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBFinalizar)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jPesquisar)
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btTrocar)
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTJogoMouseClicked
        // TODO add your handling code here:
        if(jTJogo.getSelectedRow()!=-1){            
            //txtCasa.setText(jTJogo.getValueAt(jTJogo.getSelectedRow(), 1).toString());

        }else{
            JOptionPane.showMessageDialog(null,"Selecione!!!!");
        }
        
    }//GEN-LAST:event_jTJogoMouseClicked

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        // TODO add your handling code here:
        Tipo tipo = new Tipo();
        Tipo tipoInser = new Tipo();
        TipoDAO tipdao = new TipoDAO();
        
        if(jTJogo.getSelectedRow()!=-1){   
             ProximoJogo jogo = new ProximoJogo();
             ProximoJogoDAO dao = new ProximoJogoDAO();
             
             jogo.setResultado(Double.parseDouble(txtResultado.getText()));
             if(txtStatus.getSelectedItem().equals("V")){
                    jogo.setStatus("VITORIA");             
             }else{
                 jogo.setStatus("DERROTA");
             }
                  
             jogo.setCodpro(Integer.parseInt(jTJogo.getValueAt(jTJogo.getSelectedRow(), 0).toString()));
             dao.updateStatus(jogo);

             readJTable();
        }
    }//GEN-LAST:event_jBFinalizarActionPerformed

    private void jPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesquisarActionPerformed
        // TODO add your handling code here:

            System.setProperty("webdriver.chrome.driver", "C:\\Users\\Bernardo\\Documents\\NetBeansProjects\\1 - Outros\\chromedriver.exe");
 
            WebDriver driver = new ChromeDriver(); 
            driver.get("https://www.google.com/");

            WebElement element = driver.findElement(By.name("q"));
            String Casa = jTJogo.getValueAt(jTJogo.getSelectedRow(), 2).toString();
            String Visitantes = jTJogo.getValueAt(jTJogo.getSelectedRow(), 3).toString();
            element.sendKeys(Casa+" x "+Visitantes);
            element.submit();


    }//GEN-LAST:event_jPesquisarActionPerformed

    private void btTrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTrocarActionPerformed
        // TODO add your handling code here:
        readJTableFinalizados();
    }//GEN-LAST:event_btTrocarActionPerformed
    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTJogo.getModel();
        modelo.setNumRows(0);
        ProximoJogoDAO dao = new ProximoJogoDAO();
        
        for (Iterator<ProximoJogo> it = dao.readStatus().iterator(); it.hasNext();) {
            ProximoJogo j = it.next();
            modelo.addRow(new Object[]{
                j.getCodpro(),
                j.getData(),
                j.getCasa(),
                j.getVisitante(),
                j.getPrevisao(),
                j.getStatus(),j.getT1(),
                j.getT2(),j.getLiga(),j.getResultado()
            });
        }  
        
            
    }
    
    public void readJTableFinalizados(){
        DefaultTableModel modelo = (DefaultTableModel) jTJogo.getModel();
        modelo.setNumRows(0);
        ProximoJogoDAO dao = new ProximoJogoDAO();
        
        for (Iterator<ProximoJogo> it = dao.readFinalizados().iterator(); it.hasNext();) {
            ProximoJogo j = it.next();
            modelo.addRow(new Object[]{
                j.getCodpro(),
                j.getData(),
                j.getCasa(),
                j.getVisitante(),
                j.getPrevisao(),
                j.getStatus(),j.getT1(),
                j.getT2(),j.getLiga(),j.getResultado()
                    
            });
        }  
        
            
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTrocar;
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jPesquisar;
    private javax.swing.JLabel jResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTJogo;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JComboBox txtStatus;
    // End of variables declaration//GEN-END:variables
}
