package view;


import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Jogo;
import model.bean.Tipo;
import model.dao.JogoDAO;
import model.dao.TipoDAO;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bernardo
 */
public class TelaOdds1_2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaOdds1_2
     */
    public TelaOdds1_2() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jJogos.getModel();
        // IGNORE A LINHA DE CIMA, SÓ USEI PARA MOSTRA_LO DA ONDE TIREI O TABLEMODEL 
        TableRowSorter tableSorter = new TableRowSorter(modelo);
        jJogos.setRowSorter(tableSorter);
       // tableSorter.toggleSortOrder(2); // Esta linha seleciona a coluna padrão ordenada
    }

    /**
     * <ul class="event list"> //Lista dos jogoa
            <li class="com-coupon-line-new-layout layout-1">//jogo selecionado
                <div class="avb-col avb-col-inplay">
                <div class="avb-col avb-col-markets">
                    <div class="details-market market-2-runners">//odds outros
                    <div class="details-market market-3-runners">//odds
                <div class="avb-col avb-col-runners">
                    <div class="teams-container">
                        <span class="team-name">

     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btVeificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jJogos = new javax.swing.JTable();
        btAmanh = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtodds = new javax.swing.JTextField();
        btAovivo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtafavor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        btAdicionar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtAposta = new javax.swing.JTextField();
        txtoddds = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btAovivo1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 500));

        btVeificar.setText("Hoje");
        btVeificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVeificarActionPerformed(evt);
            }
        });

        jJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Liga", "Casa", "Visitante", "Odds Casa", "Odds Empate", "Odds Visitante", "Horário", "Links", "PLacarll"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jJogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jJogosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jJogos);

        btAmanh.setText("Amanhã");
        btAmanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAmanhActionPerformed(evt);
            }
        });

        jLabel1.setText("Odds abaixo de :");
        jLabel1.setPreferredSize(new java.awt.Dimension(71, 23));

        btAovivo.setText("Ao Vivo");
        btAovivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAovivoActionPerformed(evt);
            }
        });

        jButton1.setText("Abrir Link");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtafavor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "X1", "X", "2", "X2", " " }));

        jLabel7.setText("Afavor");

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        jLabel8.setText("Aposta");

        jLabel9.setText("Odds");

        btAovivo1.setText("Tudo");
        btAovivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAovivo1ActionPerformed(evt);
            }
        });

        jButton2.setText("Pré odds");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtoddds, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtafavor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addComponent(btAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btVeificar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btAmanh, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btAovivo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAovivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtodds, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVeificar)
                    .addComponent(btAmanh)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtodds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btAovivo)
                    .addComponent(btAovivo1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtafavor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtoddds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btAdicionar)))
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btVeificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVeificarActionPerformed
        // TODO add your handling code here:
            String url = "https://www.betfair.com/sport/football";
            DefaultTableModel modelo = (DefaultTableModel) jJogos.getModel();
            modelo.setNumRows(0);

            double odds=3;
            
            if(txtodds.getText()==null || txtodds.getText().trim().equals("")){}else{odds=Double.parseDouble(txtodds.getText());}

            Document document;
        try {
            document = Jsoup.connect(url).get();
            
            Elements lala = document.select("[class=section]:eq(1)");
            Elements elements = lala.select("[class=event-list]");
            Elements itemsTimes = elements.select("[class*=com-coupon-line-new-layout]");//jogo selecionado            
            
            for(Element element : itemsTimes){
                String share = element.select("[class*=team-name]:eq(0)").text();
                String share1 = element.select("[class*=team-name]:eq(1)").text();
                
                Elements probabilidades1x2 = element.select("[class=details-market market-3-runners]");
                String horario = element.select("[class=ui-no-score]").text();
                
                Elements links = element.select("[class=ui-nav event-team-container ui-top event-link ui-gtm-click]:eq(0)");
                String linkHrefs = links.attr("href"); 
                
                //pegar nome da liga
                /*
                String url1 = "https://www.betfair.com"+linkHrefs;
                Document documentoNomeLiga = Jsoup.connect(url1).get();
                String classNomeLiga = documentoNomeLiga.select("[id*=mod-matchheader]").select("[class=ui-nav competition-info]").text();
                */
                String classNomeLiga ="";
                //odds casa
                Elements oddsCasa;
                double oddsCasa1 =0 ;                
                try {
                    oddsCasa = probabilidades1x2.select("[class*=selection sel-0]");
                    oddsCasa1 = Double.parseDouble(oddsCasa.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
                
                Elements oddsEmpate;
                double oddsEmpate1 = 0;
                try {
                    oddsEmpate = probabilidades1x2.select("[class*=selection sel-1]");
                    oddsEmpate1 = Double.parseDouble(oddsEmpate.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
            
                Elements oddsVisitante;
                double oddsVisitante1 = 0;
                try {
                    oddsVisitante = probabilidades1x2.select("[class*=selection sel-2]");
                    oddsVisitante1 = Double.parseDouble(oddsVisitante.select("[class*=ui-runner-price]").text());
                    
                } catch (Exception e) {
                }
                
                if(oddsCasa1<=odds || oddsVisitante1<=odds){
                    modelo.addRow(new Object[]{classNomeLiga,share,share1,oddsCasa1,oddsEmpate1,oddsVisitante1,horario,linkHrefs});               
                }  
                    
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaOdds1_2.class.getName()).log(Level.SEVERE, null, ex);
        }
            
       
    }//GEN-LAST:event_btVeificarActionPerformed

    private void btAmanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAmanhActionPerformed
        // TODO add your handling code here:
        
        JComponent comp = (JComponent) jJogos.getCellRenderer(0, 2);
        comp.setForeground(new Color(255,255,128));
        String url = "https://www.betfair.com/sport/football";
            DefaultTableModel modelo = (DefaultTableModel) jJogos.getModel();
            modelo.setNumRows(0);
            
            double odds=3;
            
            if(txtodds.getText()==null || txtodds.getText().trim().equals("")){}else{odds=Double.parseDouble(txtodds.getText());}

            Document document;
        try {
            document = Jsoup.connect(url).get();
            
            Elements lala = document.select("[class=section]:eq(2)");
            Elements elements = lala.select("[class=event-list]");
            Elements itemsTimes = elements.select("[class*=com-coupon-line-new-layout]");//jogo selecionado            
            
            for(Element element : itemsTimes){
                String share = element.select("[class*=team-name]:eq(0)").text();
                String share1 = element.select("[class*=team-name]:eq(1)").text();
                
                Elements probabilidades1x2 = element.select("[class=details-market market-3-runners]");
                String horario = element.select("[class=ui-no-score]").text();
                
                Elements links = element.select("[class=ui-nav event-team-container ui-top event-link ui-gtm-click]:eq(0)");
                String linkHrefs = links.attr("href");  
                
                //pegar nome da liga
                
                String url1 = "https://www.betfair.com"+linkHrefs;
                Document documentoNomeLiga = Jsoup.connect(url1).get();
                String classNomeLiga = documentoNomeLiga.select("[id*=mod-matchheader]").select("[class=ui-nav competition-info]").text();
                
                //odds casa
                Elements oddsCasa;
                double oddsCasa1 =0 ;                
                try {
                    oddsCasa = probabilidades1x2.select("[class*=selection sel-0]");
                    oddsCasa1 = Double.parseDouble(oddsCasa.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
                
                Elements oddsEmpate;
                double oddsEmpate1 = 0;
                try {
                    oddsEmpate = probabilidades1x2.select("[class*=selection sel-1]");
                    oddsEmpate1 = Double.parseDouble(oddsEmpate.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
            
                Elements oddsVisitante;
                double oddsVisitante1 = 0;
                try {
                    oddsVisitante = probabilidades1x2.select("[class*=selection sel-2]");
                    oddsVisitante1 = Double.parseDouble(oddsVisitante.select("[class*=ui-runner-price]").text());
                    
                } catch (Exception e) {
                }
                
                if(oddsCasa1<=odds || oddsVisitante1<=odds){
                    modelo.addRow(new Object[]{classNomeLiga,share,share1,oddsCasa1,oddsEmpate1,oddsVisitante1,horario,linkHrefs});             
                }  
  
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaOdds1_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAmanhActionPerformed

    private void btAovivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAovivoActionPerformed
        // TODO add your handling code here:
        String url = "https://www.betfair.com/sport/football";
            DefaultTableModel modelo = (DefaultTableModel) jJogos.getModel();
            modelo.setNumRows(0);
            
            double odds=3;
            
            if(txtodds.getText()==null || txtodds.getText().trim().equals("")){}else{odds=Double.parseDouble(txtodds.getText());}


            Document document;
        try {
            document = Jsoup.connect(url).get();
            
            Elements lala = document.select("[class=section]:eq(0)");
            Elements elements = lala.select("[class=event-list]");
            Elements itemsTimes = elements.select("[class*=com-coupon-line-new-layout]");//jogo selecionado            
            
            for(Element element : itemsTimes){
                String share = element.select("[class*=team-name]:eq(0)").text();
                String share1 = element.select("[class*=team-name]:eq(1)").text();
                
                Elements probabilidades1x2 = element.select("[class=details-market market-3-runners]");
                String horario = element.select("[class=event-inplay-state inplay ui-time-stop-format ]").text();
                String placar = element.select("[class=ui-score-container inplaynow-score score-template-default]").text();
                
                
                Elements links = element.select("[class=ui-nav event-team-container ui-top event-link ui-gtm-click]:eq(0)");
                String linkHrefs = links.attr("href");  
                
                //pegar nome da liga
                /*
                String url1 = "https://www.betfair.com"+linkHrefs;
                Document documentoNomeLiga = Jsoup.connect(url1).get();
                String classNomeLiga = documentoNomeLiga.select("[id*=mod-matchheader]").select("[class=ui-nav competition-info]").text();
                */
                String classNomeLiga ="";
                
                //odds casa
                Elements oddsCasa;
                double oddsCasa1 =0 ;                
                try {
                    oddsCasa = probabilidades1x2.select("[class*=selection sel-0]");
                    oddsCasa1 = Double.parseDouble(oddsCasa.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
                
                Elements oddsEmpate;
                double oddsEmpate1 = 0;
                try {
                    oddsEmpate = probabilidades1x2.select("[class*=selection sel-1]");
                    oddsEmpate1 = Double.parseDouble(oddsEmpate.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
                //String oddsEmpate1 = oddsEmpate.select("[class*=ui-runner-price]").text();
                
                Elements oddsVisitante;
                double oddsVisitante1 = 0;
                try {
                    oddsVisitante = probabilidades1x2.select("[class*=selection sel-2]");
                    oddsVisitante1 = Double.parseDouble(oddsVisitante.select("[class*=ui-runner-price]").text());
                    
                } catch (Exception e) {
                }
                
                //String oddsVisitante1 = oddsVisitante.select("[class*=ui-runner-price]").text();
                
                if(oddsCasa1<=odds || oddsVisitante1<=odds){
                    modelo.addRow(new Object[]{classNomeLiga,share,share1,oddsCasa1,oddsEmpate1,oddsVisitante1,horario,linkHrefs,placar});             
                }  
  
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaOdds1_2.class.getName()).log(Level.SEVERE, null, ex);
        }
 
    }//GEN-LAST:event_btAovivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
            String ss=jJogos.getValueAt(jJogos.getSelectedRow(), 7).toString();
            String aaa="https://www.betfair.com"+ss;
            URI link = new URI("https://www.betfair.com"+ss);
            Desktop.getDesktop().browse(link);

            
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jJogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jJogosMouseClicked
        // TODO add your handling code here:
        Double oddsCasa = Double.parseDouble(jJogos.getValueAt(jJogos.getSelectedRow(), 2).toString());
        Double oddsVisitantes = Double.parseDouble(jJogos.getValueAt(jJogos.getSelectedRow(), 4).toString());
        
        if(oddsCasa>oddsVisitantes){
            txtoddds.setText(oddsVisitantes.toString());
        }else{txtoddds.setText(oddsCasa.toString());}

    }//GEN-LAST:event_jJogosMouseClicked

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:

        Jogo j = new Jogo();
        JogoDAO dao = new JogoDAO();
        
        Tipo tipo = new Tipo();
        Tipo tipoInser = new Tipo();
        TipoDAO tipdao = new TipoDAO();
        
        
        if(jJogos.getSelectedRow()!=-1){       
            Date data = new Date(System.currentTimeMillis());
            j.setTimeA(jJogos.getValueAt(jJogos.getSelectedRow(), 0).toString());
            j.setTimeB(jJogos.getValueAt(jJogos.getSelectedRow(), 1).toString());
            j.setAfavor(txtafavor.getSelectedItem().toString());
            j.setAposta(Double.parseDouble(txtAposta.getText()));
            j.setOdds(Double.parseDouble(txtoddds.getText()));
            j.setRetorno((j.getAposta()*j.getOdds())-j.getAposta());
            j.setData(data.toString());
            j.setCoddtip(28);
            dao.create(j);
            
            tipo.setCodtip(28);
            tipoInser=tipdao.readRetorno(tipo);
            tipdao.updateTipo(tipoInser);

        }else{
            JOptionPane.showMessageDialog(null,"Selecione!!!!");
        }
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btAovivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAovivo1ActionPerformed
        // TODO add your handling code here:
        String url = "https://www.betfair.com/sport/football";
            DefaultTableModel modelo = (DefaultTableModel) jJogos.getModel();
            modelo.setNumRows(0);

            double odds=3;
            
            if(txtodds.getText()==null || txtodds.getText().trim().equals("")){}else{odds=Double.parseDouble(txtodds.getText());}

            Document document;
        try {
            document = Jsoup.connect(url).get();
            
            Elements lala = document.select("[class=section]");
            Elements elements = lala.select("[class=event-list]");
            Elements itemsTimes = elements.select("[class*=com-coupon-line-new-layout]");//jogo selecionado            
            
            for(Element element : itemsTimes){
                String share = element.select("[class*=team-name]:eq(0)").text();
                String share1 = element.select("[class*=team-name]:eq(1)").text();
                
                Elements probabilidades1x2 = element.select("[class=details-market market-3-runners]");
                String horario = element.select("[class=ui-no-score]").text();
                
                Elements links = element.select("[class=ui-nav event-team-container ui-top event-link ui-gtm-click]:eq(0)");
                String linkHrefs = links.attr("href");  
                
                //pegar nome da liga
                
                String url1 = "https://www.betfair.com"+linkHrefs;
                Document documentoNomeLiga = Jsoup.connect(url1).get();
                String classNomeLiga = documentoNomeLiga.select("[id*=mod-matchheader]").select("[class=ui-nav competition-info]").text();
                
                //odds casa
                Elements oddsCasa;
                double oddsCasa1 =0 ;                
                try {
                    oddsCasa = probabilidades1x2.select("[class*=selection sel-0]");
                    oddsCasa1 = Double.parseDouble(oddsCasa.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
                
                Elements oddsEmpate;
                double oddsEmpate1 = 0;
                try {
                    oddsEmpate = probabilidades1x2.select("[class*=selection sel-1]");
                    oddsEmpate1 = Double.parseDouble(oddsEmpate.select("[class*=ui-runner-price]").text());
                } catch (Exception e) {
                }
            
                Elements oddsVisitante;
                double oddsVisitante1 = 0;
                try {
                    oddsVisitante = probabilidades1x2.select("[class*=selection sel-2]");
                    oddsVisitante1 = Double.parseDouble(oddsVisitante.select("[class*=ui-runner-price]").text());
                    
                } catch (Exception e) {
                }
                
                if(oddsCasa1<=odds || oddsVisitante1<=odds){
                    modelo.addRow(new Object[]{classNomeLiga,share,share1,oddsCasa1,oddsEmpate1,oddsVisitante1,horario,linkHrefs});               
                }  
                    
            }
        } catch (IOException ex) {
            Logger.getLogger(TelaOdds1_2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAovivo1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\Bernardo\\Documents\\NetBeansProjects\\1 - Outros\\chromedriver.exe");
 
            WebDriver driver = new ChromeDriver(); 
            driver.get("https://www.google.com/");

            WebElement element = driver.findElement(By.name("q"));
            String Casa = jJogos.getValueAt(jJogos.getSelectedRow(), 1).toString();
            String Visitantes = jJogos.getValueAt(jJogos.getSelectedRow(), 2).toString();
            element.sendKeys(Casa+" x "+Visitantes+" odds pedia");
            element.submit();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAmanh;
    private javax.swing.JButton btAovivo;
    private javax.swing.JButton btAovivo1;
    private javax.swing.JButton btVeificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jJogos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAposta;
    private javax.swing.JComboBox txtafavor;
    private javax.swing.JTextField txtoddds;
    private javax.swing.JTextField txtodds;
    // End of variables declaration//GEN-END:variables
}
